name: Deploy production

on:
  push:
    branches: [ master ]
env:
  SERVICE_NAME: activestudy

jobs:
  push-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $SERVICE_NAME

      - name: Login into github container regestry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
